name: Cleanup Old Releases and Orphaned Tags

on:
  schedule:
    - cron: '2 0 * * *'  # Every day  at 01:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    env:
      KEEP_RELEASES: 5  # 🔧 Number of releases to keep

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to get full tag list

      - name: Set up GitHub CLI
        run: |
          echo "Downloading GitHub CLI..."
          curl -fsSL -o gh.deb https://github.com/cli/cli/releases/latest/download/gh_$(curl -s https://api.github.com/repos/cli/cli/releases/latest | jq -r '.tag_name' | sed 's/^v//')_linux_amd64.deb || {
            echo "Failed to download GitHub CLI."
            exit 1
          }

          echo "Installing GitHub CLI..."
          sudo dpkg -i gh.deb || {
            echo "Failed to install GitHub CLI."
            exit 1
          }

          gh --version

      - name: Authenticate and delete old releases
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_PAT }}
        run: |
          export GITHUB_TOKEN="${GH_TOKEN}"

          echo "Checking GitHub CLI authentication..."
          if ! gh auth status > /dev/null 2>&1; then
            echo "GitHub CLI is not authenticated. Exiting."
            exit 1
          fi

          echo "Fetching releases..."
          RELEASES=$(gh release list --limit 1000 2>/dev/null | awk '{print $1}')
          if [ -z "$RELEASES" ]; then
            echo "No releases found or failed to list releases."
            exit 0
          fi

          DELETE_COUNT=$(echo "$RELEASES" | wc -l)
          DELETE_COUNT=$((DELETE_COUNT - KEEP_RELEASES))

          if [ "$DELETE_COUNT" -le 0 ]; then
            echo "No old releases to delete. Keeping latest $KEEP_RELEASES."
          else
            echo "$RELEASES" | tail -n +"$((KEEP_RELEASES + 1))" | while read -r tag; do
              if [ -n "$tag" ]; then
                echo "Deleting release: $tag"
                if ! gh release delete "$tag" --yes; then
                  echo "⚠️ Failed to delete release: $tag"
                fi
                echo "Deleting tag: $tag"
                if ! git push --delete origin "$tag"; then
                  echo "⚠️ Failed to delete tag: $tag"
                fi
              fi
            done
          fi

          echo "✅ Old release cleanup complete."

      - name: Delete orphaned tags (tags without releases)
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_PAT }}
        run: |
          export GITHUB_TOKEN="${GH_TOKEN}"

          echo "🔍 Checking for orphaned tags..."
          ALL_TAGS=$(git tag)
          RELEASE_TAGS=$(gh release list --limit 1000 --json tagName --jq '.[].tagName')

          ALL_TAGS_SORTED=$(echo "$ALL_TAGS" | sort)
          RELEASE_TAGS_SORTED=$(echo "$RELEASE_TAGS" | sort)

          ORPHAN_TAGS=$(comm -23 <(echo "$ALL_TAGS_SORTED") <(echo "$RELEASE_TAGS_SORTED"))

          if [ -z "$ORPHAN_TAGS" ]; then
            echo "✅ No orphaned tags to delete."
          else
            echo "$ORPHAN_TAGS" | while read -r tag; do
              if [ -n "$tag" ]; then
                echo "🧼 Deleting orphan tag: $tag"
                if ! git push --delete origin "$tag"; then
                  echo "⚠️ Failed to delete orphan tag: $tag"
                fi
              fi
            done
            echo "✅ Orphan tag cleanup complete."
          fi

