name: Delete Old Workflow Runs

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 04:00 UTC
  workflow_dispatch:     # Allow manual run

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh jq -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.HOMEBREW_TAP_PAT }}" | gh auth login --with-token

      - name: Delete Workflow Runs Older Than 30 Days
        run: |
          REPO="${{ github.repository }}"
          echo "Cleaning up runs for $REPO"
          gh run list --repo "$REPO" --limit 1000 --json databaseId,createdAt,status | \
          jq -c '.[] | select(.status != "in_progress" and (.createdAt | fromdateiso8601 < (now - 30*86400))) | .databaseId' | \
          xargs -r -I % gh run delete % --repo "$REPO" --yes

