name: Build and cache on tag push

on:
  push:
    tags:
      - '*'  # Trigger for all version tags

jobs:
  build:
    uses: dmlane/github-workflows/.github/workflows/build-and-cachix.yml@main
    # Remove the following 2 lines if you ever want to build on Ubuntu as well
    with:
      oses: '["macos-latest"]'
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

